'use strict';
const $=s=>document.querySelector(s), encoder=new TextEncoder();let api,catalog=[],running=false,stopped=false,outputs=[],rows=[],previewURL=null,zipURL=null;
const LIMIT=300*1024*1024;
function selected(){return [...document.querySelectorAll('[data-job]:checked')].map(c=>catalog[+c.dataset.job])}
function estimate(){const n=$('#files').files.length,m=selected().length,total=n*m;$('#fileSummary').textContent=n+'张素材';$('#estimate').textContent=n+'张素材 × '+m+'个模板 = '+total+'张效果图';$('#start').disabled=running||!api||!n||!m||total>200;if(total>200)$('#estimate').textContent+='（请减少到200个组合以内）'}
function log(s){$('#log').textContent+=s+'\n';$('#log').scrollTop=$('#log').scrollHeight}
function clean(s){return s.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,100)||'image'}
function setBusy(v){running=v;document.querySelectorAll('#files,#all,#none,[data-job],[data-product-all]').forEach(e=>e.disabled=v);$('#stop').disabled=!v;estimate()}
const table=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
function crc32(a){let n=0xffffffff;for(const b of a)n=table[(n^b)&255]^(n>>>8);return (n^0xffffffff)>>>0}
function header(n){const b=new Uint8Array(n);return {b,v:new DataView(b.buffer)}}
async function zipStore(files){let offset=0,centralSize=0;const parts=[],central=[];for(const f of files){const name=encoder.encode(f.name),a=new Uint8Array(await f.blob.arrayBuffer()),crc=crc32(a),l=header(30);l.v.setUint32(0,0x04034b50,true);l.v.setUint16(4,20,true);l.v.setUint16(6,0x800,true);l.v.setUint32(14,crc,true);l.v.setUint32(18,a.length,true);l.v.setUint32(22,a.length,true);l.v.setUint16(26,name.length,true);parts.push(l.b,name,f.blob);const c=header(46);c.v.setUint32(0,0x02014b50,true);c.v.setUint16(4,20,true);c.v.setUint16(6,20,true);c.v.setUint16(8,0x800,true);c.v.setUint32(16,crc,true);c.v.setUint32(20,a.length,true);c.v.setUint32(24,a.length,true);c.v.setUint16(28,name.length,true);c.v.setUint32(42,offset,true);central.push(c.b,name);centralSize+=46+name.length;offset+=30+name.length+a.length;}const end=header(22);end.v.setUint32(0,0x06054b50,true);end.v.setUint16(8,files.length,true);end.v.setUint16(10,files.length,true);end.v.setUint32(12,centralSize,true);end.v.setUint32(16,offset,true);return new Blob([...parts,...central,end.b],{type:'application/zip'})}
async function run(files,jobs){if(running)throw Error('已有任务运行中');if(!files.length||!jobs.length||files.length*jobs.length>200)throw Error('请选择1至200个组合');outputs=[];rows=[];stopped=false;if(zipURL){URL.revokeObjectURL(zipURL);zipURL=null}$('#download').disabled=true;$('#log').textContent='';setBusy(true);const total=files.length*jobs.length;let done=0,bytes=0;$('#progress').max=total;$('#progress').value=0;try{outer:for(let i=0;i<files.length;i++){const file=files[i];for(const job of jobs){if(stopped)break outer;const name=String(i+1).padStart(3,'0')+'_'+clean(file.name.replace(/\.[^.]+$/,''))+'/'+job.sku+'/'+job.scene+'.png';try{const blob=await api.render(file,job);if(bytes+blob.size>LIMIT){log('达到300MB限制，已保留已完成结果，请分批继续。');stopped=true;break outer}bytes+=blob.size;outputs.push({name,blob});rows.push({file:file.name,sku:job.sku,scene:job.scene,status:'success',output:name});if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(blob);$('#preview').src=previewURL;$('#preview').hidden=false;}catch(e){rows.push({file:file.name,sku:job.sku,scene:job.scene,status:'failed',error:e.message});log(file.name+' / '+job.sku+' / '+job.scene+'：'+e.message)}done++;$('#progress').value=done;$('#status').textContent='已处理 '+done+'/'+total+'，成功 '+outputs.length;await new Promise(r=>setTimeout(r,0));}}}finally{setBusy(false);$('#download').disabled=!rows.length;$('#status').textContent=(stopped?'已停止':'已完成')+'：成功 '+outputs.length+'，失败 '+rows.filter(r=>r.status==='failed').length+'，未处理 '+(total-done);log('已完成结果可下载ZIP。');}return {total,done,success:outputs.length,rows}}
$('#files').onchange=estimate;$('#all').onclick=()=>{document.querySelectorAll('[data-job]').forEach(e=>e.checked=true);estimate()};$('#none').onclick=()=>{document.querySelectorAll('[data-job]').forEach(e=>e.checked=false);estimate()};$('#stop').onclick=()=>{stopped=true;$('#status').textContent='正在停止，将保留当前任务完成的图片…'};$('#start').onclick=()=>run([...$('#files').files],selected()).catch(e=>log(e.message));
async function packageResults(){return zipStore([...outputs,{name:'生成记录.json',blob:new Blob([JSON.stringify({created:new Date().toISOString(),stopped,rows},null,2)],{type:'application/json'})}])}
$('#download').onclick=async()=>{$('#download').disabled=true;try{const zip=await packageResults();if(zipURL)URL.revokeObjectURL(zipURL);zipURL=URL.createObjectURL(zip);const a=document.createElement('a');a.href=zipURL;a.download='商品效果图-'+new Date().toISOString().replace(/[:.]/g,'-')+'.zip';a.click()}catch(e){log('打包失败：'+e.message)}finally{$('#download').disabled=false}};
function init(){const candidate=$('#engine').contentWindow.batchAPI;if(!candidate?.ready()){const err=$('#engine').contentDocument.querySelector('#error')?.textContent;if(err){$('#status').textContent=err;return}setTimeout(init,250);return}api=candidate;catalog=api.catalog();$('#templates').textContent='';for(const product of [...new Set(catalog.map(j=>j.product))]){const jobs=catalog.filter(j=>j.product===product),field=document.createElement('fieldset'),legend=document.createElement('legend'),all=document.createElement('input');all.type='checkbox';all.dataset.productAll=product;legend.append(all,document.createTextNode(jobs[0].label.split(' / ')[0]));field.append(legend);for(const job of jobs){const label=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.dataset.job=catalog.indexOf(job);c.onchange=estimate;label.append(c,document.createTextNode(' '+job.scene+' · '+job.sku));field.append(label)}all.onchange=()=>{field.querySelectorAll('[data-job]').forEach(c=>c.checked=all.checked);estimate()};$('#templates').append(field)}$('#all').disabled=$('#none').disabled=false;$('#status').textContent='模板就绪，请选择素材和模板';estimate()}
$('#engine').addEventListener('load',init);if($('#engine').contentDocument?.readyState==='complete')init();
window.batchTest={run,packageResults,get catalog(){return catalog},get rows(){return rows},get outputs(){return outputs},stop:()=>stopped=true};
