let libraryItems=[];
function libraryMode(){return $('sourceMode').value==='library'}
function libraryCount(){const n=$('variants').rows.length,m=libraryItems.length;if(libraryMode()){$('specCount').textContent=m+'条素材 × '+n+'条规格 → '+m+'个父体 + '+(m*n)+'个子体';$('preview').textContent='检查所选记录（'+m*(n+1)+'行）';$('generate').textContent='从已保存结果生成商品表格';$('preview').disabled=$('generate').disabled=busy||!m}else{$('generate').textContent='生成图片和草稿表格到文件夹';$('preview').disabled=$('generate').disabled=busy||!api?.ready()}}
const refreshDirect=refreshSpecs;refreshSpecs=function(){refreshDirect();libraryCount()};
function changeSource(){for(const id of ['file','product','designId','subject','detail'])$(id).closest('label').hidden=libraryMode();$('librarySelectionPanel').hidden=!libraryMode();$('urls').closest('details').hidden=libraryMode();$('rows').replaceChildren();$('issues').replaceChildren();$('downloads').replaceChildren();refreshSpecs()}
function currentItems(){return [...$('selectedRecords').children].map(el=>({id:el.dataset.id,subject:el.querySelector('[data-subject]').value,detail:el.querySelector('[data-detail]').value}))}
function libraryInput(){const p=payload();p.items=currentItems();return p}
function renderSelected(){const container=$('selectedRecords');container.replaceChildren();for(const item of libraryItems){const card=document.createElement('div');card.dataset.id=item.id;card.className='saved-selection';const title=document.createElement('strong');title.textContent=item.sourceName+' · '+item.productSku+' · '+Object.keys(item.images).length+'张效果图';card.append(title);let saved={};try{saved=JSON.parse(localStorage.getItem('listing-text-'+item.id)||'{}')}catch{}
 for(const [key,label,type]of [['subject','此素材英文主题','input'],['detail','此素材英文描述','textarea']]){const l=document.createElement('label'),field=document.createElement(type);l.textContent=label;if(type==='input')field.type='text';field.dataset[key]='';field.maxLength=key==='subject'?65:500;field.value=saved[key]||'';field.setAttribute('aria-label',item.sourceName+' '+label);l.append(field);card.append(l);field.oninput=()=>{$('rows').replaceChildren();$('downloads').replaceChildren();$('status').textContent='素材文案已修改，请重新检查并生成表格。';try{localStorage.setItem('listing-text-'+item.id,JSON.stringify({subject:card.querySelector('[data-subject]').value,detail:card.querySelector('[data-detail]').value}))}catch{}}}
 container.append(card)}libraryCount()}
async function loadLibrarySelection(){try{const ids=JSON.parse(sessionStorage.getItem('librarySelection')||'[]');if(!ids.length){libraryItems=[];renderSelected();return}const r=await fetch('/api/library');if(!r.ok)throw Error('读取生成列表失败');const all=(await r.json()).items;libraryItems=ids.map(id=>all.find(x=>x.id===id&&x.status==='saved'&&['landscape','portrait'].includes(x.product))).filter(Boolean);renderSelected();$('libraryNotice').textContent='已选择'+libraryItems.length+'条帆布画。每条素材的主题和描述分别填写；共用下方规格、报价和包装配置。公网图片链接仍待补充。单次最多500条素材，合计不超过10000行；超过请分批。'}catch(e){$('libraryNotice').textContent=e.message}}
const directPreview=$('preview').onclick,directGenerate=$('generate').onclick;
$('preview').onclick=async()=>{if(!libraryMode())return directPreview();try{const plan=await request('preview-library',libraryInput());show({...plan,rows:plan.rows.slice(0,200),issues:plan.issues.slice(0,200)});$('status').textContent='已检查：'+plan.designs.length+'个父体 + '+plan.variants.length+'个子体。'+(plan.rows.length>200?'仅展示前200行，导出包含全部记录。':'')}catch(e){$('status').textContent=e.message}};
$('generate').onclick=async()=>{if(!libraryMode())return directGenerate();try{const input=libraryInput();lock(true);$('status').textContent='正在根据已保存记录生成表格，不会重新渲染图片…';const result=await request('generate-library',input);$('downloads').replaceChildren();for(const f of result.files){const a=document.createElement('a');a.href=f.url;a.download=f.name;a.textContent='下载 '+f.name;$('downloads').append(a,document.createElement('br'))}$('status').textContent='已保存商品表格草稿，共'+result.rows+'行。点击下方下载；图片仍保存在生成列表中。尚未上传亚马逊。'}catch(e){$('status').textContent=e.message}finally{lock(false);libraryCount()}};
$('sourceMode').onchange=changeSource;$('reloadSelection').onclick=loadLibrarySelection;changeSource();loadLibrarySelection();

const directInit=init;init=function(){directInit();if(libraryMode()){libraryCount();if(api?.ready())$('status').textContent='请选择已保存结果并填写商品文案，检查记录后生成表格。'}};
