const $=id=>document.getElementById(id);let items=[],limit=50;const selected=new Set();try{const ids=JSON.parse(sessionStorage.getItem('librarySelection')||'[]');if(Array.isArray(ids))ids.forEach(id=>selected.add(id))}catch{}
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
const eligible=r=>r.status==='saved'&&['landscape','portrait'].includes(r.product);
const asset=(r,s)=>'/api/library/'+r.id+'/asset/'+s;
function filtered(){const q=$('search').value.toLowerCase();return items.filter(r=>($('filter').value==='all'||r.product===$('filter').value)&&[r.sourceName,r.productSku].join(' ').toLowerCase().includes(q))}
function count(){sessionStorage.setItem('librarySelection',JSON.stringify([...selected]));$('toListing').disabled=!selected.size;$('status').textContent='共'+items.length+'条记录，已选择'+selected.size+'条帆布画。保存未完成的记录可在批量页用相同素材续存。'}
function draw(){const rows=filtered();$('recordList').replaceChildren();for(const r of rows.slice(0,limit)){const tr=node('tr'),check=node('input');check.type='checkbox';check.disabled=!eligible(r);check.checked=selected.has(r.id);check.setAttribute('aria-label','选择 '+r.sourceName+' '+r.productSku);check.onchange=()=>{check.checked?selected.add(r.id):selected.delete(r.id);count()};const cells=Array.from({length:6},()=>node('td'));cells[0].append(check);const scene=Object.keys(r.images)[0];if(scene){const img=node('img');img.className='record-thumb';img.loading='lazy';img.src=asset(r,scene);img.alt=r.sourceName;cells[1].append(img)}cells[2].className='record-name';cells[2].append(node('strong',r.sourceName),node('div',r.productSku));cells[3].textContent=(r.status==='saved'?'已保存':'保存未完成')+' · '+Object.keys(r.images).length+'/'+r.scenes.length+'张';cells[4].textContent=new Date(r.created).toLocaleString();const view=node('button','查看图片');view.onclick=()=>detail(r);cells[5].append(view);tr.append(...cells);$('recordList').append(tr)}$('more').hidden=rows.length<=limit;count()}
function detail(r){$('detailTitle').textContent=r.sourceName+' · '+r.productSku;$('sourceDownload').href=asset(r,'source');$('sourceDownload').download=r.sourceName;$('sourceDownload').hidden=!r.source;$('detailImages').replaceChildren();for(const scene of Object.keys(r.images)){const f=node('figure'),im=node('img'),a=node('a','下载 '+scene);im.src=asset(r,scene);im.alt=scene;im.loading='lazy';a.href=asset(r,scene);a.download=r.productSku+'-'+scene+'.png';f.append(im,a);$('detailImages').append(f)}$('detailDialog').showModal()}
async function refresh(){try{items=(await LibraryClient.request('')).items;for(const id of selected)if(!items.some(r=>r.id===id&&eligible(r)))selected.delete(id);draw()}catch(e){$('status').textContent='读取失败：'+e.message}}
$('refresh').onclick=refresh;$('search').oninput=$('filter').onchange=()=>{limit=50;draw()};$('selectAll').onclick=()=>{filtered().filter(eligible).forEach(r=>selected.add(r.id));draw()};$('clear').onclick=()=>{selected.clear();draw()};$('more').onclick=()=>{limit+=50;draw()};$('closeDetail').onclick=()=>$('detailDialog').close();$('toListing').onclick=()=>{if(selected.size>500){$('status').textContent='单次最多选择500条，请分批处理';return}sessionStorage.setItem('librarySelection',JSON.stringify([...selected]));location.href='/listing.html'};refresh();
