'use strict';
const $=id=>document.getElementById(id),scenes=['white','light','dark','scene3','scene4','scene5','scene6','other'],keys=['price','quantity','handling','weight','length','width','height','packageWeight'];let api,busy=false,urls=[];
function variantRows(){return [...$('variants').rows].map(tr=>Object.fromEntries([...tr.querySelectorAll('[data-key]')].map(i=>[i.dataset.key,i.value])))}
function refreshSpecs(){
 const n=$('variants').rows.length;$('specCount').textContent=n+'条规格 → 1个父体 + '+n+'个子体';$('preview').textContent='检查'+(n+1)+'条商品记录';$('addVariant').disabled=busy||n>=VariantConfig.MAX;
 [...$('variants').rows].forEach((tr,i)=>{tr.querySelector('[data-remove]').disabled=busy||n<=1;tr.querySelector('[data-remove]').setAttribute('aria-label','删除第'+(i+1)+'条规格');for(const el of tr.querySelectorAll('[data-key]'))el.setAttribute('aria-label','第'+(i+1)+'行 '+({frame:'框型',widthIn:'宽度英寸',heightIn:'高度英寸',price:'售价',quantity:'库存',handling:'处理天数',weight:'净重',length:'包装长',width:'包装宽',height:'包装高',packageWeight:'包装重'}[el.dataset.key]))});
}
function invalidateSpecs(){refreshSpecs();$('rows').replaceChildren();$('issues').replaceChildren();$('downloads').replaceChildren();$('status').textContent='规格已修改，请重新检查商品记录。尺寸改变不会重绘效果图模板。'}
function addVariant(v={frame:'framed',widthIn:'',heightIn:''}){
 const tr=document.createElement('tr');
 for(const k of ['frame','widthIn','heightIn',...keys]){
  const cell=document.createElement('td'),el=document.createElement(k==='frame'?'select':'input');el.dataset.key=k;
  if(k==='frame'){for(const [value,label]of [['framed','有框'],['unframed','无框']]){const o=document.createElement('option');o.value=value;o.textContent=label;el.append(o)}}
  else{el.type='number';el.min=['widthIn','heightIn'].includes(k)?'0.01':'0';el.step=['quantity','handling'].includes(k)?'1':['widthIn','heightIn'].includes(k)?'0.01':'any';if(['widthIn','heightIn'].includes(k))el.max='120'}
  el.value=v[k]??'';cell.append(el);tr.append(cell);
 }
 const cell=document.createElement('td'),button=document.createElement('button');button.type='button';button.textContent='删除';button.dataset.remove='';button.onclick=()=>{tr.remove();invalidateSpecs()};cell.append(button);tr.append(cell);$('variants').append(tr);
}
function setVariantRows(rows){$('variants').replaceChildren();rows.forEach(addVariant);refreshSpecs()}
setVariantRows(VariantConfig.defaults($('product').value));
$('variants').addEventListener('input',invalidateSpecs);
$('addVariant').onclick=()=>{if($('variants').rows.length>=VariantConfig.MAX)return;addVariant();invalidateSpecs()};
$('resetVariants').onclick=()=>{if(!confirm('恢复默认10条规格会清空当前规格的售价、库存和包装参数，是否继续？'))return;setVariantRows(VariantConfig.defaults($('product').value));invalidateSpecs()};
for(const scene of scenes){const label=document.createElement('label'),input=document.createElement('input');label.textContent=scene;input.type='text';input.dataset.scene=scene;label.append(input);$('urls').append(label)}
function payload(){const data={market:$('market').value,product:$('product').value,sourceFile:$('file').files[0]?.name||'',variantSchema:2,variants:VariantConfig.normalize(variantRows()),mapping:Object.fromEntries(['framed','unframed'].map(k=>[k,$(k).value.split(',').map(s=>s.trim()).filter(Boolean)])),images:Object.fromEntries([...document.querySelectorAll('[data-scene]')].map(e=>[e.dataset.scene,e.value]))};for(const k of ['designId','subject','detail','keywords','brand','origin','shipping'])data[k]=$(k).value;for(const k of ['gtinExempt','singlePiece','mappingConfirmed'])data[k]=$(k).checked;return data}
async function request(route,data){const r=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),p=await r.json();if(!r.ok)throw Error(p.error||'生成失败');return p}
function show(plan){$('issues').replaceChildren();for(const issue of plan.issues){const li=document.createElement('li');li.textContent=issue;$('issues').append(li)}$('rows').replaceChildren();for(const row of plan.rows){const tr=document.createElement('tr');for(const k of ['A','D','G','BG','BH','GD']){const td=document.createElement('td');td.textContent=row[k]??'';tr.append(td)}$('rows').append(tr)}}
function lock(v){busy=v;document.querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=v);refreshSpecs()}
$('preview').onclick=async()=>{try{const p=await request('preview',payload());show(p);$('status').textContent='已检查：1个父体 + '+p.variants.length+'个子体。以下待补项保留为空。'}catch(e){$('status').textContent=e.message}};
$('saveConfig').onclick=()=>{try{const p=payload();for(const k of ['designId','subject','detail','keywords','sourceFile','images'])delete p[k];const u=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='产品配置.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){$('status').textContent=e.message}};
$('loadConfig').onchange=async()=>{try{const file=$('loadConfig').files[0];if(!file)return;if(file.size>100000)throw Error('配置文件过大');const p=JSON.parse(await file.text());const specs=VariantConfig.normalize(p.variants,{allowLegacy:p.variantSchema!==2});p.market=p.market||'UK';if(!['UK','CA'].includes(p.market))throw Error('不支持的站点配置');for(const k of ['market','product','brand','origin','shipping'])if(typeof p[k]==='string')$(k).value=p[k];for(const k of ['singlePiece','gtinExempt','mappingConfirmed'])$(k).checked=p[k]===true;setVariantRows(specs);$('rows').replaceChildren();$('issues').replaceChildren();$('downloads').replaceChildren();for(const k of ['framed','unframed'])if(Array.isArray(p.mapping?.[k]))$(k).value=p.mapping[k].join(',');marketLabels();$('status').textContent='已加载'+$('market').value+'产品配置'}catch(e){$('status').textContent=e.message}};
$('generate').onclick=async()=>{let output;try{const file=$('file').files[0];if(!file)throw Error('请选择一张素材');if(!window.showDirectoryPicker)throw Error('请使用Chrome或Edge的目录保存功能');const base=await window.showDirectoryPicker({mode:'readwrite'});lock(true);const data=payload(),plan=await request('preview',data);show(plan);output=await base.getDirectoryHandle('JD-'+data.market+'-'+data.designId+'-'+Date.now(),{create:true});const images=await output.getDirectoryHandle('images',{create:true});for(const u of urls)URL.revokeObjectURL(u);urls=[];$('gallery').replaceChildren();$('downloads').replaceChildren();const jobs=api.catalog().filter(j=>j.product===data.product);for(let i=0;i<jobs.length;i++){const job=jobs[i];$('status').textContent=`生成效果图 ${i+1}/${jobs.length}：${job.scene}`;const b=await api.render(file,job);await ProductBatch.write(images,job.scene+'.png',b);const im=document.createElement('img');im.alt=job.scene;im.src=URL.createObjectURL(b);urls.push(im.src);$('gallery').append(im)}await ProductBatch.write(output,'图片对应清单.json',new Blob([JSON.stringify(plan.imageMap,null,2)]));$('status').textContent='图片已保存，正在生成XLSM草稿并校验…';const result=await request('generate',data);for(const f of result.files){const r=await fetch(f.url);if(!r.ok)throw Error('读取导出文件失败：'+f.name);await ProductBatch.write(output,f.name,await r.blob());const a=document.createElement('a');a.href=f.url;a.textContent=f.name;a.download=f.name;$('downloads').append(a,document.createElement('br'))}$('status').textContent=`完成：${jobs.length}张效果图 + 1个父体 + ${plan.variants.length}个子体，保存到 ${output.name}。这是待补字段的草稿，未上传亚马逊。`}catch(e){$('status').textContent=e.name==='AbortError'?'已取消选择':e.message+(output?'。已保存的图片保留在 '+output.name:'')}finally{lock(false)}};
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue=''}});
function init(){api=$('engine').contentWindow.batchAPI;if(!api?.ready()){const err=$('engine').contentDocument.querySelector('#error')?.textContent;if(err){$('status').textContent=err;return}setTimeout(init,300);return}$('preview').disabled=$('generate').disabled=false;$('status').textContent='模板已加载。先填写素材信息，预览记录，再生成到文件夹。'}
$('engine').addEventListener('load',init);

function marketLabels(){const ca=$('market').value==='CA';$('priceLabel').textContent='售价'+(ca?'CAD':'GBP');$('shippingLabel').textContent=(ca?'加拿大':'英国')+'站配送模板名'}
$('market').onchange=()=>{document.querySelectorAll('[data-key=price]').forEach(e=>e.value='');$('shipping').value='';$('rows').replaceChildren();$('issues').replaceChildren();$('downloads').replaceChildren();marketLabels();$('status').textContent='已切换站点，售价和配送模板已清空，请按目标站点重新填写或加载配置。'};
